server:
  port: 8040

spring:
  application:
    name: microservice-gateway-zuul

eureka:
  client:
    serviceUrl:
      ##设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka;多个地址间可用,分割
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  security:
    enabled: false

zuul:
  ignored-services: '*'
  routes:
    movie-route:
      service-id: microservice-consumer-movie
      #url: http://localhost:8010/ #指定的url
      path: /movie/**